version: '2.2'
services:
    redis:
        image: 'redis:5.0.5'
        command: redis-server --requirepass redispass
        network_mode: "host"

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - /data/airflow/postgres:/var/lib/postgresql/data/pgdata
        network_mode: "host"

    webserver:
        image: piboonsak/ais-airflow:temp-4
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
            - PYTHONPATH=/usr/local/airflow/conf/
        volumes:
            - /data/airflow/airflow/dags:/usr/local/airflow/dags
            - /data/airflow/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - /data/airflow/airflow/logs:/usr/local/airflow/logs
            - /data/airflow/airflow/conf:/usr/local/airflow/conf
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        network_mode: "host"
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: piboonsak/ais-airflow:temp-4
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            - REDIS_PASSWORD=redispass
        network_mode: "host"
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: piboonsak/ais-airflow:temp-4
        restart: always
        depends_on:
            - webserver
        volumes:
            - /data/airflow/airflow/dags:/usr/local/airflow/dags
            - /data/airflow/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - /data/airflow/airflow/logs:/usr/local/airflow/logs   
            - /data/airflow/airflow/conf:/usr/local/airflow/conf
        # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        network_mode: "host"
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
            - PYTHONPATH=/usr/local/airflow/conf/
        command: scheduler

    worker:
        image: piboonsak/ais-airflow:temp-4
        restart: always
        depends_on:
            - scheduler
        volumes:
            - /data/airflow/airflow/dags:/usr/local/airflow/dags
            - /data/airflow/airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
            - /data/airflow/airflow/logs:/usr/local/airflow/logs   
            - /data/airflow/airflow/conf:/usr/local/airflow/conf  
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        network_mode: "host"
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - REDIS_PASSWORD=redispass
            - PYTHONPATH=/usr/local/airflow/conf/
        command: worker